Feature: GridStruct
mlee03/FMSgridtools pull request #3
Opened 2024-12-23 16:36 UTC by fmalatino

**Description**
This PR adds the `GridStruct` shared class as base Python `dataclass` for other grid classes/structs. It contains the minimum data necessary to specify a grid. The class currently contains methods for reading in grid data from a file, and writing out grid data to a file. I/O method(s) are currently in development for data management when in use with heterogeneous architectures. 

**Tested**
A Unit test to ensure proper functionality of the read and write to file methods is contained within `fmsgridtools/tests/shared/test_gridstruct.py`. As new methods are implemented, relevant tests will be also be added to this file and others that may depend on the `GridStruct` class.

2025-01-07 14:20 UTC, mlee03 commented
Could you add @rem1776 to the list of reviewers?

2025-01-07 14:23 UTC, mlee03 requested changes

2025-01-07 14:23 UTC, mlee03 commented on gridtools/shared/GridStruct.py
> +
It needs dimension info too

2025-01-07 14:23 UTC, mlee03 commented on gridtools/shared/GridStruct.py
> +    def write_out_grid(self, file_path: str):
will you use this function to write out all gridfiles?  The metadata values will differ for different types of grid

2025-01-07 14:23 UTC, mlee03 commented on gridtools/shared/GridStruct.py
> +                units="degree_east",
All these metadata vlues will vary with different types of grids

2025-01-07 17:16 UTC, fmalatino commented on gridtools/shared/GridStruct.py
> +
Dimension as in layout? Or some other attribute?

2025-01-07 17:17 UTC, fmalatino commented on gridtools/shared/GridStruct.py
> +    def write_out_grid(self, file_path: str):
Should there be no metadata or should the metadata become attributes that can be defined if need be?

2025-01-09 21:16 UTC, rem1776 approved these changes

2025-01-09 21:23 UTC, mlee03 commented on gridtools/shared/GridObj.py
> +    north_pole: str = None
north_pole, proejction, discretization, conformal, are they make_hgrid user-specified options?

2025-01-09 21:29 UTC, mlee03 commented on gridtools/shared/GridObj.py
> +                geometry = ds.tile.attrs["geometry"],
debating if we need to store these metadata, and if so, should we store the metadata for all the other variables.. :thinking:

2025-01-09 21:34 UTC, mlee03 requested changes

2025-01-09 21:34 UTC, mlee03 commented on gridtools/shared/GridObj.py
> +                geometry = ds.tile.attrs["geometry"],
We should store the metadata values for other variables for example as a dictionary or in some other organized fashion.  Then the dict can be referenced when writing out the grid files.

2025-01-10 13:44 UTC, fmalatino commented on gridtools/shared/GridObj.py
> +                geometry = ds.tile.attrs["geometry"],
I will add an attribute to `GridObj` that can hold this dictionary and will amend the write_out method to use this dictionary.

2025-01-10 14:19 UTC, mlee03 commented
Food for thought, I'm wondering instead of reinventing the wheel, can we leverage the classes/objects that xarray provides.  Can we hold whatever data arrays  as xarray's DataArray or  [Coordinates](https://docs.xarray.dev/en/stable/generated/xarray.Coordinates.html).  One benefit of that is it would be much easier to write out the data @fmalatino @rem1776 @hderry

2025-01-10 14:25 UTC, fmalatino commented
> Food for thought, I'm wondering instead of reinventing the wheel, can we leverage the classes/objects that xarray provides. Can we hold whatever data arrays as xarray's DataArray or [Coordinates](https://docs.xarray.dev/en/stable/generated/xarray.Coordinates.html). One benefit of that is it would be much easier to write out the data @fmalatino @rem1776 @hderry

That would be great! I will dig into the literature and see what I can come up with. And if any of you have any suggestions regarding its use send it my way please.

2025-01-13 19:23 UTC, mlee03 commented on gridtools/shared/GridObj.py
> +            return cls(grid=ds, gridfile=filepath)
Nice.  Good idea with having a from_file function as a classmethod.  Does this define self.grid as well though?  Or is that going to be a separate function?

2025-01-13 19:38 UTC, fmalatino commented on gridtools/shared/GridObj.py
> +            return cls(grid=ds, gridfile=filepath)
Yes it does, in the return of the function setting `grid=ds` will initialize the grid attribute of the instance with a xarray dataset. Accessing the variables of the dataset is then done by:
```
grid_obj = GridObj.from_file("/location/of/netcdf")

data_x = grid_obj.grid.x.values                     # <class 'numpy.ndarray'>

name = grid_obj.grid.x.attrs["standard_name"]       # <class 'str'>
```

2025-01-13 19:57 UTC, mlee03 commented on gridtools/shared/GridObj.py
> +            return cls(grid=ds, gridfile=filepath)
nice!

2025-01-13 19:59 UTC, mlee03 approved these changes

2025-01-13 20:00 UTC, merged